### ISSUE TITLE
downgrade pandas to 1.1.5

### ISSUE THREAD

**Issue by zaza** [jedrzejd/scrap-otomoto#1]
Not sure why but for me installing pandas 1.2.1 as defined in Requirements.txt failed with:

`Collecting pandas==1.2.1 (from -r Requirements.txt (line 7))
  Could not find a version that satisfies the requirement pandas==1.2.1 (from -r Requirements.txt (line 7)) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 0.25.0rc0, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0rc0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0rc0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
No matching distribution found for pandas==1.2.1 (from -r Requirements.txt (line 7))
`

This was when running `python3 -m pip install -r Requirements.txt`.

I downgraded the dependency to 1.1.5 and it appears to run smoothly. Is it safe to keep it downgraded?

sweet app btw!

**Comment by jedrzejd** [comment]
Thanks for the information.
You may have old version PyPI, try ```pip install --upgrade pip```

**Comment by zaza** [comment]
The latest version of pandas requires Python 3.7, so I had to install deps with `python3.7 -m pip install -r Requirements.txt`.

**Comment by zaza** [comment]
sorry, reopening. imho this should be closes once the readme is updated: https://github.com/jedrzejd/scrap-otomoto/pull/5

**Comment by zaza** [comment]
the pull request has been merged.

**Comment by jedrzejd** [comment]
I merge your commit. 
Thanks for searching and fixing issues in the project.
