### ISSUE TITLE
Looking for 'warszawa' the car returns ads from Warszawa the city

### ISSUE THREAD

**Issue by zaza** [jedrzejd/scrap-otomoto#3]
https://www.otomoto.pl/osobowe/warszawa returns all ads from the city of Warszawa (over 13000). the correct url for the car is: https://www.otomoto.pl/osobowe/marka_warszawa/ with only a handful of results.

**Comment by jedrzejd** [comment]
I push commit with fixing your issue.

**Comment by zaza** [comment]
looks good. thanks!
